services:
  - type: web
    name: vietnam-quant-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GEMINI_API_KEY
        sync: false
      - key: REDIS_URL
        fromDatabase:
          name: vietnam-quant-redis
          property: connectionString

databases:
  - name: vietnam-quant-redis
    plan: free
    ipAllowList: []
